# Update srcs/docker-compose.yml
version: "3.8"

services:

  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - web_volume:/var/www/html
      - ./requirements/nginx/conf:/etc/nginx/conf.d
    networks:
      inception:
    restart: unless-stopped
    depends_on:
      - wordpress
    env_file:
      - .env

  wordpress:
    build:
      context: ./requirements/wordpress/.
      dockerfile: Dockerfile
    container_name: wp-php
    volumes:
      - web_volume:/var/www/html
    networks:
      inception:
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./requirements/mariadb/.
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      inception:
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql
      - ./requirements/mariadb/conf:/etc/mysql/conf.d
    restart: unless-stopped

volumes:
  web_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/g0dr1c/data/web
  db_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/g0dr1c/data/db

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt