version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - wp_network
    volumes:
      - wp_data:/var/www/html
      - ./secrets:/run/secrets:ro
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    networks:
      - wp_network
    volumes:
      - wp_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD_FILE=${MYSQL_PASSWORD_FILE}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    secrets:
      - db_password
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    networks:
      - wp_network
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=${MYSQL_ROOT_PASSWORD_FILE}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=${MYSQL_PASSWORD_FILE}
    secrets:
      - db_root_password
      - db_password
    restart: unless-stopped

volumes:
  wp_data:
  db_data:

networks:
  wp_network:

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt